#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: names_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/db.d 

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: names_db
    depends_on:
      - postgres

volumes:
  postgres_data:
